name: All Workflows
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  call-operating-systems:
    uses: ./.github/workflows/os.yml

  call-ides:
    uses: ./.github/workflows/ide.yml
