name: All Workflows
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  FaunaDB:
    uses: ./.github/workflows/faunadb.yml
    secrets:
      FAUNADB_API_KEY: ${{ secrets.FAUNADB_API_KEY }}

  Github:
    needs: FaunaDB
    uses: ./.github/workflows/github_repos.yml
    secrets:
      FAUNADB_API_KEY: ${{ secrets.FAUNADB_API_KEY }}


  X-Ray:
    needs: FaunaDB
    uses: ./.github/workflows/xray_targets.yml
    secrets:
      FAUNADB_API_KEY: ${{ secrets.FAUNADB_API_KEY }}