name: All Workflows
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  X-Ray:
    uses: ./.github/workflows/xray_targets.yml
    secrets:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

  Github:
    uses: ./.github/workflows/github_repos.yml