name: FaunaDB
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FAUNADB_API_KEY:
        required: true
  

jobs:

  clear:

    runs-on: ubuntu-latest

    steps:

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Install FaunaDB
        run: |
          npm i -g fauna-shell
          echo "Map( Paginate( Documents(Collection('versions')), { size: 9999 } ), Lambda( ['ref'], Delete(Var('ref'))))" | fauna eval --stdin --secret=${{ secrets.FAUNADB_API_KEY }}