name: Github Repos
on:
  workflow_dispatch:
  workflow_call:
  
env:
  category: ide

jobs:

  get:

    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: 'microsoft/vscode'
          - repo: 'notepad-plus-plus/notepad-plus-plus'
          #   file: 'ide-notepad++.json'
          # - repo: 'atom/atom'
          #   file: 'ide-atom.json'
          # - repo: 'textmate/textmate'
          #   file: 'ide-textmate.json'

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/${{ matrix.repo }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - run: | 
          echo '${{ steps.get_latest_release.outputs.data }}' | tr '\r\n' ' ' > ./data.json
          cat ./data.json


      - name: Get the repo details
        uses: sergeysova/jq-action@v2
        id: get_repo_details
        with:
          cmd: "jq '.[] | select( .repo | contains(\"${{ matrix.repo }}\") )' ./sources/github.json  -r > ./source.json"


      - name: Get Release tag_name
        uses: sergeysova/jq-action@v2
        id: release_tag_name
        with:
          cmd: "jq '{id: .[1].id, title: .[1].title, version: .[0].tag_name, link: .[1].download, published_at: .[0].published_at}' -s ./data.json ./source.json  -r > ./results.json"


      - run: | 
          cat ./results.json


      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     message: 'Update'
      #     add: './results/${{ env.category }}/${{ matrix.repo }}.json'



      # "id"     : target.id,
      # "title"  : target.title,
      # "version": version,
      # "link"   : target.download,
      # "date"   : date.toGMTString()