name: Github Repos
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AIRTABLE_API_KEY:
        required: true
  
env:
  category: ide

jobs:

  get:

    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: 'microsoft/vscode'
          - repo: 'notepad-plus-plus/notepad-plus-plus'
          #   file: 'ide-notepad++.json'
          # - repo: 'atom/atom'
          #   file: 'ide-atom.json'
          # - repo: 'textmate/textmate'
          #   file: 'ide-textmate.json'

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/${{ matrix.repo }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - run: | 
          echo '${{ steps.get_latest_release.outputs.data }}' | tr '\r\n' ' ' > ./data.json
          cat ./data.json


      - name: Get the repo details
        uses: sergeysova/jq-action@v2
        id: get_repo_details
        with:
          cmd: "jq '.[] | select( .repo | contains(\"${{ matrix.repo }}\") )' ./sources/github.json  -r > ./source.json"


      - name: Get Release tag_name
        uses: sergeysova/jq-action@v2
        id: release_tag_name
        with:
          cmd: "jq '{id: .[1].id, title: .[1].title, version: .[0].tag_name, link: .[1].download, published_at: .[0].published_at}' -s ./data.json ./source.json  -r > ./results.json"


      - name: Push to Airtable
        run: | 
          cat ./results.json
          cat ./results.json | curl -v \
            -X POST \
            -H "Content-Type: application/json" \ 
            -H "Authorization: Bearer ${{ secrets.AIRTABLE_API_KEY }}" \
            -X POST \
            --data @- https://api.airtable.com/v0/app8NMPBTR6QCoYX2/versions
