name: IDEs
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

env:
  category: ide

jobs:

  getRelease:

    strategy:
      fail-fast: false
      matrix:
        repo: [
          'microsoft/vscode', 
          'notepad-plus-plus/notepad-plus-plus',
          'atom/atom',
          'textmate/textmate',
          ]

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/${{ matrix.repo }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - run: | 
          mkdir -p results/${{ env.category }}/${{ matrix.repo }}
          echo '${{ steps.get_latest_release.outputs.data }}' | tr '\r\n' ' ' > ./results/${{ env.category }}/${{ matrix.repo }}.release.json
          cat ./results/${{ env.category }}/${{ matrix.repo }}.release.json


      - name: Get Release tag_name
        uses: sergeysova/jq-action@v2
        id: release_tag_name
        with:
          cmd: "jq '{latest_version: .tag_name, html_url: .html_url, published_at: .published_at}' ./results/${{ env.category }}/${{ matrix.repo }}.release.json -r > ./results/${{ env.category }}/${{ matrix.repo }}.json"



      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update'
          add: './results/${{ env.category }}/${{ matrix.repo }}.json'