name: Operating Systems
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AIRTABLE_API_KEY:
        required: true

jobs:
  getRelease:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'


      - shell: bash
        name: Run Scrape
        run: |
          cp ./x-ray/os_targets.json ./targets.json
          npm install
          node --no-warnings scrape.js

      - shell: bash
        name: Send to Airtable
        run: |
          echo 'AIRTABLE_API_KEY="${{ secrets.AIRTABLE_API_KEY }}"' >> .env
          node --no-warnings export_airtable.js