name: Operating Systems
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  config: 'os_targets.js'

jobs:
  getRelease:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'


      - shell: bash
        name: Run Scrape
        run: |
          echo 'AIRTABLE_API_KEY="${{ secrets.AIRTABLE_API_KEY }}"' >> .env
          cp ./x-ray/os_targets.json ./targets.json
          npm install
          node --no-warnings scrape.js