name: OS - WINDOWS
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  filename: 'microsoft_windows.js'

jobs:

  getRelease:


    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'


      - shell: bash
        name: Run Scrape
        run: |
          AIRTABLE_API_KEY="${{ secrets.AIRTABLE_API_KEY }}"
          npm install
          node --no-warnings ./x-ray/${{ env.filename }}
