name: OS - WINDOWS
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  filename: 'microsoft_windows.js'

jobs:

  getRelease:


    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'


      - shell: bash
        run: |
          AIRTABLE_API_KEY="${{ secrets.AIRTABLE_API_KEY }}"
          npm install
          NODE_DEBUG=cluster,net,http,fs,tls,module,timers
          echo "FILE=$(node ./x-ray/${{ env.filename }})" >> $GITHUB_ENV


      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     message: 'Update'
      #     add: '${{ env.FILE }}'