name: OS - WINDOWS
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

env:
  filename: 'microsoft_windows.js'
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

jobs:

  getRelease:


    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: | 
          echo "AIRTABLE_API_KEY=$(echo $AIRTABLE_API_KEY | cut -c 1-6)" >> $GITHUB_ENV
          echo $AIRTABLE_API_KEY

      - run: | 
          npm install
          echo "FILE=$(node --no-warnings ./x-ray/${{ env.filename }})" >> $GITHUB_ENV


      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update'
          add: '${{ env.FILE }}'