name: OS
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

env:
  filename: 'apple_macos.js'


jobs:

  getRelease:


      
    runs-on: ubuntu-latest


    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'


      - run: | 
          npm install
          echo "FILE=$(node --no-warnings ./x-ray/${{ env.filename }})" >> $GITHUB_ENV


      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update'
          add: '${{ env.FILE }}'