name: Microsoft/VSCode
on:
  push:
    branches:
      - master

jobs:

  getLatestVersion:

    runs-on: ubuntu-latest
    steps:

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: microsoft
          repo: vscode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data.tag_name }}'"

      - run: "echo 'latest headers: ${{ steps.get_latest_release.outputs.headers }}'"

      - run: "echo 'latest status: ${{ steps.get_latest_release.outputs.status }}'"

      - run: "echo 'latest data: ${{ steps.get_latest_release.outputs.data }}'"