name: X-Ray Targets
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FAUNADB_API_KEY:
        required: true

jobs:

  get:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: '16'


      - shell: bash
        name: Run Scrape
        run: |
          echo 'FAUNADB_API_KEY="${{ secrets.FAUNADB_API_KEY }}"' >> .env
          cp ./sources/xray.json ./targets.json
          npm install
          node --no-warnings scrape-json.js

      
      - name: Install FaunaDB
        run: |
          npm i -g fauna-shell


      - name: Import Data
        run: |         
          fauna import --append --secret=${{ secrets.FAUNADB_API_KEY }} --collection=versions --path ./results.json